trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
      echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
  displayName: Setup Java

- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true

- script: nuget install dotNETFramework
  displayName: Install .NET Framework

- script: install.bat
  displayName: Install JCC