trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x86'
    jdkSourceOption: 'PreInstalled'

- script: install.bat
  displayName: Install JCC